"""
Convert the "Temperature Data" and "Humidity Data" sheets in
BAS Savings Calc Template.xlsm into one committed JS data file,
app/data/bas-weather-bins.js, used by the BAS Savings Calc (app/calculators.js).

Source workbook (not committed - read-only reference):
  C:\\Users\\Matt Miller\\AI\\_context\\my-knowledge-base\\raw\\Calcs\\BAS Savings Calc Template.xlsm

Layout notes: see
  C:\\Users\\Matt Miller\\AI\\_context\\temp\\2026-09-22-bas-calc-weather\\2026-09-22-layout.txt

Usage:
  python tools/generate-bas-weather-data.py
Run from the repo root (or any cwd - paths below are absolute).
"""

import json
import openpyxl

SRC = r"C:\Users\Matt Miller\AI\_context\my-knowledge-base\raw\Calcs\BAS Savings Calc Template.xlsm"
OUT = r"C:\Users\Matt Miller\AI\_context\temp\2026-09-22-bas-calc-weather-worktree\app\data\bas-weather-bins.js"

MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Full bin set observed across all 17 locations in both Data sheets (descending).
BINS = [107.5, 102.5, 97.5, 92.5, 87.5, 82.5, 77.5, 72.5, 67.5, 62.5,
        57.5, 52.5, 47.5, 42.5, 37.5, 32.5, 27.5, 22.5, 17.5, 12.5,
        7.5, 2.5, -2.5]
BIN_INDEX = {b: i for i, b in enumerate(BINS)}

# Name fixups vs. the raw sheet text (typo correction, consistent short form).
NAME_FIX = {
    "Wichita, Kansas": "Wichita, KS",
    "Balitmore, MD": "Baltimore, MD",
    "New York, NY (La Guardia)": "New York, NY",
}


def find_blocks(ws):
    """Return list of (row, id, name) header rows, in row order."""
    blocks = []
    for r in range(1, ws.max_row + 1):
        a = ws.cell(r, 1).value
        b = ws.cell(r, 2).value
        if isinstance(a, (int, float)) and float(a).is_integer() and isinstance(b, str):
            blocks.append((r, int(a), b))
    return blocks


def extract_sheet(ws):
    """Return {location_id: {name, grid: [12][23][24]}} for one Data sheet."""
    blocks = find_blocks(ws)
    out = {}
    for bi, (start_row, loc_id, name) in enumerate(blocks):
        if loc_id == 17:
            continue  # blank "City, ST" template slot - not real data
        end_row = blocks[bi + 1][0] - 1 if bi + 1 < len(blocks) else ws.max_row
        grid = [[[0.0] * 24 for _ in range(len(BINS))] for _ in range(12)]
        month_idx = None
        for r in range(start_row + 4, end_row + 1):
            bin_val = ws.cell(r, 2).value
            month_val = ws.cell(r, 4).value
            if month_val is not None:
                if month_val not in MONTHS:
                    continue
                month_idx = MONTHS.index(month_val)
            if bin_val is None or month_idx is None:
                continue
            if not isinstance(bin_val, (int, float)):
                continue
            if bin_val not in BIN_INDEX:
                raise ValueError(f"Unexpected bin {bin_val} at row {r} in block {name}")
            b_idx = BIN_INDEX[bin_val]
            for h in range(24):
                v = ws.cell(r, 5 + h).value  # col E = hour 1
                grid[month_idx][b_idx][h] = float(v) if isinstance(v, (int, float)) else 0.0
        out[loc_id] = {"name": NAME_FIX.get(name, name), "grid": grid}
    return out


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    temp = extract_sheet(wb["Temperature Data"])
    hum = extract_sheet(wb["Humidity Data"])

    ids = sorted(set(temp.keys()) & set(hum.keys()))
    cities = {}
    for cid in ids:
        cities[cid] = {
            "name": temp[cid]["name"],
            "temp": temp[cid]["grid"],
            "humidity": hum[cid]["grid"],
        }

    payload = {"bins": BINS, "months": [m[:3].upper() for m in MONTHS], "cities": cities}

    js = (
        "/* AUTO-GENERATED by tools/generate-bas-weather-data.py - do not hand-edit.\n"
        "   Source: BAS Savings Calc Template.xlsm, sheets \"Temperature Data\" and \"Humidity Data\".\n"
        "   temp[monthIdx][binIdx][hourIdx] = hours of occurrence (typical year).\n"
        "   humidity[monthIdx][binIdx][hourIdx] = grains of moisture per lb dry air (divide by 7000\n"
        "   for lb/lb humidity ratio - see 2026-09-22-layout.txt for the Excel formula this mirrors).\n"
        "   bins[] = descending temperature bin midpoints (degrees F), shared index for temp and humidity. */\n"
        "const BAS_WEATHER_BINS = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {OUT} ({len(js):,} bytes), {len(ids)} cities.")


if __name__ == "__main__":
    main()
